language: swift
osx_image: xcode9.3
xcode_project: SplayDict.xcworkspace
xcode_scheme: SplayDict-Example
xcode_sdk: iphonesimulator11.2
sudo: required

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update
  - pod repo update


